apiVersion: v1
appVersion: 6.0.1
description: Podinfo Helm chart for Kubernetes
home: https://github.com/satya-dillikar/podinfo
kubeVersion: '>=1.19.0-0'
maintainers:
- email: satya-dillikar@users.noreply.github.com
  name: satya-dillikar
name: podinfo
sources:
- https://github.com/satya-dillikar/podinfo
version: 7.0.0
