apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: plugins-config
    configMap:
      name: {{ .Release.Name }}-configmap
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: plugins-config
      mountPath: /config
      readOnly: true
  hostNetwork: true
  dnsPolicy: Default